"""pythonprojecthw.ipynb
Automatically generated by Colab.
Original file is located at
    https://colab.research.google.com/drive/1szAMHoFk2BivJ-8RDsvKTo29VJll7_y-
"""
# 한글 폰트 설정
rc('font', family='NanumBarunGothic')
plt.rcParams['axes.unicode_minus'] = False  # 마이너스 기호 처리


import pandas as pd
import numpy as np



df = pd.read_csv('서울교통공사_지하철혼잡도정보_20241231.csv', encoding = 'cp949')

#data casting to list
data = []
dataCongestion = []
dataCongestionAverage = []
dataCongestionMorningRushAverage = []#출근 시간 혼잡도 평균
dataCongestionAfternoonAverage = []#그 외 시간 혼잡도 평균
dataCongestionEveningRushAverage = []#퇴근 시간 혼잡도 평균
dataCongestionNightAverage = []# 야간 시간  혼잡도 평균
listResult = []

for i in range(0, len(df)):

    df['00시30분'] = df['00시30분'].fillna(0)
    data.append(list(df.iloc[i]))
    dataCongestion.append(list(df.iloc[i][6 : 45]))
    dataCongestionAverage.append(np.average(dataCongestion[i]))
    dataCongestionMorningRushAverage.append(np.average(dataCongestion[i][0 : 9]))
    dataCongestionAfternoonAverage.append(np.average(dataCongestion[i][9 : 25]))
    dataCongestionEveningRushAverage.append(np.average(dataCongestion[i][25 : 31]))
    dataCongestionNightAverage.append(np.average(dataCongestion[i][31 : ]))
    listResult.append([df.iloc[i, 1]] +
            [df.iloc[i, 4]] +
            [df.iloc[i, 5]] +
            [dataCongestionAverage[i]] +
            [dataCongestionMorningRushAverage[i]] +
            [dataCongestionAfternoonAverage[i]] +
            [dataCongestionEveningRushAverage[i]] +
            [dataCongestionNightAverage[i]])



column_names = ['요일구분', '출발역', '상하구분', '혼잡도 전체평균', '혼잡도 출근시간 평균', '혼잡도 그 외 시간 평균', '혼잡도 퇴근시간 평균', '혼잡도 야간시간 평균']

#dfResult = pd.DataFrame(listResult, columns = column_names)
#dfResult

#df.iloc[행 인덱스, 열 이름]

dfResult = pd.DataFrame(listResult, columns = column_names)

dfResult['요일출발역'] = dfResult['요일구분'] + dfResult['출발역']
dfResult.drop(['요일구분', '출발역'], axis=1, inplace=True)


dfResult.sort_values(by = ['혼잡도 전체평균'], ascending = False, inplace = True)
dfTotalTop10 = dfResult[dfResult['혼잡도 전체평균'] != 0].head(10)
dfTotalTop10
dfTotalBottom10 = dfResult[dfResult['혼잡도 전체평균'] != 0].tail(10)
dfTotalBottom10

dfResult.sort_values(by = ['혼잡도 출근시간 평균'], ascending = False, inplace = True)
dfMorningTop10 = dfResult[dfResult['혼잡도 전체평균'] != 0].head(10)
dfMorningTop10
dfMorningBottom10 = dfResult[dfResult['혼잡도 전체평균'] != 0].tail(10)
dfMorningBottom10


dfResult.sort_values(by = ['혼잡도 그 외 시간 평균'], ascending = False, inplace = True)
dfAfternoonTop10 = dfResult[dfResult['혼잡도 전체평균'] != 0].head(10)
dfAfternoonTop10
dfAfternoonBottom10 = dfResult[dfResult['혼잡도 전체평균'] != 0].tail(10)
dfAfternoonBottom10

dfResult.sort_values(by = ['혼잡도 퇴근시간 평균'], ascending = False, inplace = True)
dfEveningRushTop10 = dfResult[dfResult['혼잡도 전체평균'] != 0].head(10)
dfEveningRushTop10
dfEveningRushBottom10 = dfResult[dfResult['혼잡도 전체평균'] != 0].tail(10)
dfEveningRushBottom10

dfResult.sort_values(by = ['혼잡도 야간시간 평균'], ascending = False, inplace = True)
dfNightTop10 = dfResult[dfResult['혼잡도 전체평균'] != 0].head(10)
dfNightTop10
dfNightBottom10 = dfResult[dfResult['혼잡도 전체평균'] != 0].tail(10)
dfNightBottom10


import matplotlib.pyplot as plt

def CongestionGraph(somethingDf, congestionName, timeStr):
    plt.figure(figsize=(5, 5))
    plt.bar(somethingDf['요일출발역'], somethingDf[congestionName])
    plt.xticks(rotation=90)
    plt.xlabel('출발역')
    plt.ylabel('혼잡도(%)')
    plt.title(timeStr)
    plt.show()

CongestionGraph(dfTotalTop10, '혼잡도 전체평균', '전체')
CongestionGraph(dfMorningTop10, '혼잡도 출근시간 평균','출근 시간 혼잡도 (상위 10개)')

dfTotalTop10



# plt.figure(figsize=(5, 5))
# plt.bar(dfMorningTop10['요일출발역'], dfMorningTop10['혼잡도 출근시간 평균'])
# plt.xticks(rotation=90)
# plt.xlabel('출발역')
# plt.ylabel('혼잡도(%)')
# plt.title('출근 시간 혼잡도 (상위 10개)')
# plt.show()

# plt.figure(figsize=(5, 5))
# plt.bar(dfNightBottom10['요일출발역'], dfNightBottom10['혼잡도 야간시간 평균'])
# plt.xticks(rotation=90)
# plt.xlabel('출발역')
# plt.ylabel('혼잡도(%)')
# plt.title('야간 시간 혼잡도 (하위 10개)')
# plt.show()




# dfNightBottom10
