# -*- coding: utf-8 -*-
"""pythonprojecthw.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1szAMHoFk2BivJ-8RDsvKTo29VJll7_y-
"""

from google.colab import files
f = files.upload()

import pandas as pd
import numpy as np


df = pd.read_csv('서울교통공사_지하철혼잡도정보_20241231.csv', encoding = 'cp949')

#data casting to list
data = []
dataCongestion = []
dataCongestionAverage = []
dataCongestionMorningRushAverage = []#출근 시간 혼잡도 평균
dataCongestionAfternoonAverage = []#그 외 시간 혼잡도 평균
dataCongestionEveningRushAverage = []#퇴근 시간 혼잡도 평균
dataCongestionNightAverage = []# 야간 시간  혼잡도 평균
listResult = []

for i in range(0, len(df)):

    df['00시30분'] = df['00시30분'].fillna(0)
    data.append(list(df.iloc[i]))
    dataCongestion.append(list(df.iloc[i][6 : 45]))
    dataCongestionAverage.append(np.average(dataCongestion[i]))
    dataCongestionMorningRushAverage.append(np.average(dataCongestion[i][0 : 9]))
    dataCongestionAfternoonAverage.append(np.average(dataCongestion[i][9 : 25]))
    dataCongestionEveningRushAverage.append(np.average(dataCongestion[i][25 : 31]))
    dataCongestionNightAverage.append(np.average(dataCongestion[i][31 : ]))
    listResult.append([df.iloc[i, 4]] +
            [df.iloc[i, 5]] +
            [dataCongestionAverage[i]] +
            [dataCongestionMorningRushAverage[i]] +
            [dataCongestionAfternoonAverage[i]] +
            [dataCongestionEveningRushAverage[i]] +
            [dataCongestionNightAverage[i]])



column_names = ['출발역', '상하구분', '혼잡도 전체평균', '혼잡도 출근시간 평균', '혼잡도 그 외 시간 평균', '혼잡도 퇴근시간 평균', '혼잡도 야간시간 평균']

dfResult = pd.DataFrame(listResult, columns = column_names)
dfResult